Testing & Changes
UtsavSomaiya/point-of-sale pull request #36
Opened 2022-02-14 05:44 UTC by UtsavSomaiya

- [ ] User Id and Password are Wrong -> Incorrect credentials.
- [ ] Remove link of Forgot password.
- [ ] Display the product with less opacity if product stock not available.
- [ ] Image upload testing.(move_uploaded_file).
- [ ] Tax not pre-selected after form submit.(Testing & Chnages).
- [ ] Simple edit icon in product list.
- [ ] Same icons in category list.
- [ ] Don't delete... -> Cannot delete this category as it is used by one ore more products.
- [ ] Display existing discount.(Add the flat discount also).
- [ ] Display that it's percentage or flat.
- [ ] Validate percentage.
- [ ] Sale details page product image should be displayed.(Same as above in product_list should be working so it can be working also).
- [ ] Display Subtotal,Total_tax,Discount	Total on the sales details page.
- [ ] Why underscore version on sale details page table columns.
- [ ] Dashboard :- 

- Total sales count
- Total sales amount
- Total discount offered
- Total tax collected.

- [ ] POS :

- Clear All button should work.
- Tax should be calculated after discount applied.

2022-02-14 10:34 UTC, UtsavSomaiya commented
Done Now you can check this PR and Let me know.

2022-02-14 11:56 UTC, gauravmak requested changes

2022-02-14 11:56 UTC, gauravmak commented on admin/category/show_category.php
> +                                                src="/admin/images/1.png" /></a></a></td>
Keep in a separate directory

2022-02-14 11:56 UTC, gauravmak commented on index.php
> -                  //unset($_SESSION["msg"]);
?

2022-02-14 11:56 UTC, gauravmak commented on index.php
> +$PERCENTAGE_DISCOUNT = 1;
Use [constants](https://www.php.net/manual/en/language.constants.php)

2022-02-15 11:19 UTC, gauravmak requested changes

2022-02-15 11:19 UTC, gauravmak commented on index.php
> +define("discount", [
Should be in capital `discount`

2022-02-15 12:22 UTC, gauravmak requested changes

2022-02-15 12:22 UTC, gauravmak commented on admin/product/show_product.php
> +                                                src="/admin/image/1.png" /></a></td>
What is `1.png`? Keep proper image name

2022-02-17 05:12 UTC, merged