Discount Module In Frontend
UtsavSomaiya/point-of-sale pull request #39
Opened 2022-03-03 13:09 UTC by UtsavSomaiya

2022-03-04 07:49 UTC, hirenkeraliya requested changes

2022-03-04 07:49 UTC, hirenkeraliya commented on custom.js
> +    console.log(digit);
?

2022-03-04 07:49 UTC, hirenkeraliya commented on custom.js
> +function toggleModal(modalID) {
which modal?

2022-03-04 07:49 UTC, hirenkeraliya commented on custom.js
> +    var x = document.getElementById("snackbar");
what is x?

2022-03-04 07:49 UTC, hirenkeraliya commented on discount.php
> +                        Discounts
one tab back

2022-03-07 09:25 UTC, hirenkeraliya commented on custom.js
> +    }
Do not need else part

2022-03-07 09:29 UTC, hirenkeraliya commented on custom.js
> +function discountModal(modalId) {
displayApplicableDiscountsModal

2022-03-07 09:30 UTC, hirenkeraliya commented on discount.php
> +                            <?php for ($i=0;$i<sizeof($discounts);$i++) {?>
Proper indentation

2022-03-07 09:31 UTC, hirenkeraliya commented on discount.php
> +                                </option>
Do some readable code

2022-03-08 05:13 UTC, UtsavSomaiya commented
https://user-images.githubusercontent.com/96036522/157170640-0cc3bc48-3549-45fe-bca6-169a682a7ff0.MP4

2022-03-08 05:30 UTC, hirenkeraliya approved these changes

2022-03-08 07:24 UTC, merged