Add discount tier
UtsavSomaiya/point-of-sale pull request #47
Opened 2022-03-14 12:18 UTC by UtsavSomaiya

- [ ] In this PR we can CRUD of discount Tier

2022-03-15 04:55 UTC, hirenkeraliya requested changes

2022-03-15 04:55 UTC, hirenkeraliya commented on admin/discount/add.php
> +                ];
indentation always our first priority

2022-03-15 04:55 UTC, hirenkeraliya commented on admin/discount/add.php
> +        for ($i = 0; $i < sizeof($_POST['digit']); $i++) {
`sizeof` to `count`

2022-03-15 04:55 UTC, hirenkeraliya commented on admin/discount/add.php
> +        }
I think there is bug on the code

2022-03-15 04:55 UTC, hirenkeraliya commented on admin/discount/edit.php
> +    var index = <?= sizeof($discountTierIds) ?>;
totalDiscounts

2022-03-15 04:55 UTC, hirenkeraliya commented on admin/js/discount.js
> +var j = 1;
what is `j`?

2022-03-15 04:55 UTC, hirenkeraliya commented on admin/js/discount.js
> +var j = 1;
This mistake is repeated a second time and its last warning.

2022-03-15 04:55 UTC, hirenkeraliya commented on admin/js/discount.js
> +function addInsert() {
make proper name what mean of `addInsert`?

2022-03-15 04:55 UTC, hirenkeraliya commented on admin/js/discount.js
> +
why this 3 blank lines?

2022-03-16 07:31 UTC, hirenkeraliya approved these changes

2022-04-22 06:21 UTC, hirenkeraliya requested changes

2022-04-22 06:21 UTC, hirenkeraliya commented on admin/discount/edit.php
> +                                        if ($discountType == "1") {
elseif

2022-04-22 06:21 UTC, hirenkeraliya commented on admin/discount/edit.php
>                                              if ($discountType == "2") {
elseif

2022-04-22 06:21 UTC, hirenkeraliya commented on admin/layout/db_connect.php
> +        $pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
?

2022-04-22 06:21 UTC, hirenkeraliya commented on admin/product/add_product.php
> -        }
why?

2022-04-22 06:21 UTC, hirenkeraliya commented on custom.js
> +/* function discountApply(count) {
why comment?

2022-04-22 06:21 UTC, hirenkeraliya commented on discount.php
>                              </tr>
why commented code

2022-04-22 07:26 UTC, UtsavSomaiya commented on admin/layout/db_connect.php
> +        $pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
This is for show the pdo exception.

2022-04-25 07:39 UTC, hirenkeraliya approved these changes

2022-04-25 07:39 UTC, merged