Blog changes
UtsavSomaiya/point-of-sale pull request #48
Opened 2022-04-21 11:49 UTC by UtsavSomaiya

2022-04-22 06:24 UTC, hirenkeraliya requested changes

2022-04-22 06:24 UTC, hirenkeraliya commented on index.php
> +        <!-- https://unpkg.com/tailwindcss@2.0.2/dist/tailwind.min.css -->
why?

2022-04-22 09:37 UTC, UtsavSomaiya commented on index.php
> +        <!-- https://unpkg.com/tailwindcss@2.0.2/dist/tailwind.min.css -->
Yesterday I am on your PC but net is not available than download this package

2022-04-25 07:48 UTC, hirenkeraliya reviewed
discount.js is still using the createElement

2022-04-25 07:48 UTC, hirenkeraliya commented on cart_template.php
> +</template>
indentation?

2022-04-25 07:48 UTC, hirenkeraliya commented on cart_template.php
> +</template>
End of line?

2022-04-25 07:48 UTC, hirenkeraliya commented on custom.js
> +                alert('Stock is over!!');
Out of stock

2022-04-25 09:43 UTC, UtsavSomaiya commented
> discount.js is still using the createElement

This change is done in next PR.

2022-04-26 10:34 UTC, hirenkeraliya approved these changes

2022-04-26 10:34 UTC, merged